apply plugin: 'com.android.application'
apply plugin: 'realm-android'
apply plugin: 'org.jetbrains.kotlin.android'

android {
    compileSdk = 34
    namespace 'top.wefor.now'

    defaultConfig {
        applicationId "top.wefor.nowview"
//        applicationId "top.wefor.test.nowview"
        minSdkVersion 21
        targetSdkVersion 34
        versionCode 23
        versionName "4.2"

        buildConfigField "String", "APK_DATE", "\"${getCurrentDate()}\""
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            proguardFiles file('./proguard').listFiles()
        }
    }

    // Enable the BuildConfig feature
    buildFeatures {
        buildConfig = true
        viewBinding = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

}

// 定义获取当前日期的函数
String getCurrentDate() {
    return new Date().format("yyyy-MM-dd HH:mm")
}

realm {
    syncEnabled = true;
}

dependencies {
    implementation 'androidx.core:core-ktx:1.13.1'

    implementation fileTree(include: ['*.jar'], dir: 'libs')
    testImplementation 'junit:junit:4.13.2' // Updated to a newer JUnit version

    // AndroidX libraries
    implementation 'androidx.appcompat:appcompat:1.7.0' // Updated to AndroidX AppCompat
    implementation 'com.google.android.material:material:1.12.0' // Updated to Material Components
    implementation 'androidx.cardview:cardview:1.0.0' // Updated to AndroidX CardView
    implementation 'com.google.code.gson:gson:2.10.1' // Updated to the latest Gson

    implementation files('libs/open_sdk_r5990_lite.jar')
    implementation 'com.tencent.mm.opensdk:wechat-sdk-android-without-mta:5.1.4'

    // jsoup HTML parser library
    implementation 'org.jsoup:jsoup:1.14.3' // Updated to the latest jsoup version

    // MaterialViewpager
    implementation 'com.github.florent37:materialviewpager:1.2.3'
    implementation 'com.flaviofaria:kenburnsview:1.0.7'
    implementation 'com.jpardogo.materialtabstrip:library:1.1.0'
    implementation 'com.github.bumptech.glide:glide:4.16.0' // Updated to the latest Glide version
    annotationProcessor 'com.github.bumptech.glide:compiler:4.14.2' // Match Glide version

    // Fresco: Image loading
    implementation 'com.facebook.fresco:fresco:2.6.0' // Updated to the latest Fresco version

    implementation 'com.github.chrisbanes:PhotoView:2.3.0' // Updated to the latest PhotoView version

    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1' // Update to latest RxAndroid
    implementation 'io.reactivex.rxjava2:rxjava:2.2.21' // Update to latest RxJava
    implementation 'com.alibaba:fastjson:1.2.83' // Update to the latest Fastjson version
    implementation "com.squareup.okhttp3:okhttp:4.12.0"
    implementation "com.squareup.okhttp3:logging-interceptor:4.10.0"
    implementation "com.squareup.retrofit2:retrofit:2.11.0"
    implementation "com.squareup.retrofit2:converter-gson:2.9.0"
    implementation "com.squareup.retrofit2:adapter-rxjava2:2.9.0"

    implementation 'jp.wasabeef:recyclerview-animators:4.0.2'
    implementation 'com.orhanobut:logger:2.2.0' // Check for a newer version if available
    implementation 'com.wang.avi:library:2.1.3' // Check for a newer version if available

    // RxPermissions
    implementation 'com.tbruyelle.rxpermissions2:rxpermissions:0.9.5' // No need for '@aar'

    // Java 8 support for Lifecycles
    implementation "androidx.lifecycle:lifecycle-common-java8:2.8.6" // Updated to AndroidX Lifecycle
}